### ISSUE TITLE
in `require': cannot load such file -- yajl/2.0/yajl (LoadError)

### ISSUE THREAD

**Issue by qwertie** [poole/poole#32]
On my machine, I can use Jekyll with my own gh-pages and with jekyll-bootstrap, but Jekyll doesn't like Poole (on Windows, Ruby 2.0.0, Jekyll freshly installed today). What do you make of this error?

```
C:\Dev\poole-master>jekyll serve
Configuration file: C:/Dev/poole-master/_config.yml
   Deprecation: The 'pygments' configuration option has been renamed to 'highlighter'.
Please update your config file accordingly. The allowed values are 'rouge', 'pygments' or null.
        Source: C:/Dev/poole-master
   Destination: C:/Dev/poole-master/_site
  Generating...
Liquid Exception: cannot load such file -- yajl/2.0/yajl in _posts/2014-01-01-example-content.md
C:/Dev/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load
such file -- yajl/2.0/yajl (LoadError)
    from C:/Dev/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/yajl-ruby-1.1.0-x86-mingw32/lib/yajl/yajl.rb:2:in `<top (required)>'
    from C:/Dev/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from C:/Dev/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/yajl-ruby-1.1.0-x86-mingw32/lib/yajl.rb:1:in `<top (required)>'
    from C:/Dev/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    from C:/Dev/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from C:/Dev/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/pygments.rb-0.6.0/lib/pygments/popen.rb:3:in `<top (required)>'
    from C:/Dev/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from C:/Dev/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/pygments.rb-0.6.0/lib/pygments.rb:1:in `<top (required)>'
    from C:/Dev/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from C:/Dev/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/lib/jekyll/tags/highlight.rb:61:in `render_pygments'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/lib/jekyll/tags/highlight.rb:49:in `render'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/block.rb:109:in `block in render_all'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `each'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `render_all'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/block.rb:82:in `render'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/template.rb:128:in `render'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/liquid-2.6.1/lib/liquid/template.rb:138:in `render!'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/lib/jekyll/convertible.rb:96:in `render_liquid'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/lib/jekyll/convertible.rb:199:in `do_layout'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/lib/jekyll/post.rb:266:in `render'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/lib/jekyll/site.rb:261:in `block in render'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/lib/jekyll/site.rb:260:in `each'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/lib/jekyll/site.rb:260:in `render'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/lib/jekyll/site.rb:43:in `process'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/lib/jekyll/command.rb:53:in `process_site'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/lib/jekyll/commands/build.rb:50:in `build'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/lib/jekyll/commands/build.rb:33:in `process'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/lib/jekyll/commands/serve.rb:24:in `block (2 levels) 
    in init_with_program'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `call'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `block in execute'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `each'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `execute'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/program.rb:35:in `go'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary.rb:22:in `program'
    from C:/Dev/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.1.0/bin/jekyll:18:in `<top (required)>'
    from C:/Dev/Ruby200/bin/jekyll:23:in `load'
    from C:/Dev/Ruby200/bin/jekyll:23:in `<main>'
```

**Comment by zhaozj89** [comment]
I wonder why Pygments does not work. I have Pygments installed in my computer.

**Comment by xiaocpp** [comment]
@qwertie tks, it's work for me!
